An assortment of changes done over Summer 2016
bcipolli/DifferentialEncoding pull request #10
Opened 2016-10-03 21:22 UTC by vishaalprasad

2016-10-03 21:24 UTC, vishaalprasad commented
These are changes I made over summer. I'm not sure where the conflict is (perhaps in VisualizeDataset... I'm not quite sure why I committed those changes to begin with?) but most of it should speak for itself.

If anything is unclear, do let me know.

2016-10-05 13:30 UTC, bcipolli requested changes
Overall, looks good! A couple of fine-tuning requests re: code / comments, but otherwise seems good to go!

2016-10-05 13:30 UTC, bcipolli commented on code/_expts/slotnick_etal_2001/de_StimCreate.m
> +            if d1 == d2
I'm guessing this is the insertion to duplicate training examples. If so, I think the clearer way is to do:
```
train.X(:, end+1) = train.X(:, end);
train.XLAB{end+1} = train.XLAB{end}
```

Either way, please add a comment to this block about what you did and why.

2016-10-05 13:30 UTC, bcipolli commented on code/analyze/ac/plots/de_PlotFFTs.m
> +          rMin = min(min(imgRH));
I find `min(imgRH(:))` is a bit clearer, as it says: get the min over all dimensions. Your idiom reads: get the min over the first two dimensions; I have to know that there are only two.

2016-10-05 13:30 UTC, bcipolli commented on code/analyze/ac/plots/de_PlotFFTs.m
> +          ylabel('Normalized')
`Normalized` is an adjective. Perhaps `Normalized intensity`? Or `Normalized power`?

2016-10-05 13:30 UTC, bcipolli commented on code/analyze/ac/plots/de_PlotFFTs.m
> +          rMin = min(min(imgRH));
You actually use that idiom below. Better to use a single idiom, so highly encourage the change here.

2016-10-05 13:30 UTC, bcipolli commented on code/stim/de_VisualizeDataset.m
> +  for ii=1:min(4*4, length(im2show)) %make sure only 16 are shown
Once this constant gets duplicated, good to declare it somewhere and reuse as a constant.

2016-10-05 22:20 UTC, vishaalprasad commented on code/analyze/ac/plots/de_PlotFFTs.m
> +          ylabel('Normalized')
Well it's the pixel values that are normalized. But '''Normalized pixel''' should work?

2016-10-07 11:15 UTC, bcipolli commented
Looks good. In the future, better to make PRs against `guruucsd/DifferentialEncoding`, which is the source repo. I will make a PR of these changes there.

2016-10-07 11:15 UTC, merged